kind: ConfigMap
apiVersion: v1
metadata:
  name: hangman-config
  namespace: games
  labels:
    app.kubernetes.io/name: hangman-config
    app.kubernetes.io/instance: hangman-config
    app.kubernetes.io/version: '20201212'
    app.kubernetes.io/component: hangman
    app.kubernetes.io/part-of: games
    # app.kubernetes.io/managed-by: blazedpath
    enviroment: dev
    tier: backend
data:
  APP_HOST: http://localhost
  APP_PORT: '8000'
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hangman
  namespace: games
  labels:
    app.kubernetes.io/name: hangman
    app.kubernetes.io/instance: hangman
    app.kubernetes.io/version: '20201212'
    app.kubernetes.io/component: hangman
    app.kubernetes.io/part-of: games
    # app.kubernetes.io/managed-by: blazedpath
    enviroment: dev
    tier: frontend
  annotations:
    # prometheus.io/scrape: 'true'
    # prometheus.io/path: /metrics
    # prometheus.io/port: '8000'
    kubernetes.io/change-cause: '20201212'
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: hangman
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hangman
        app.kubernetes.io/instance: hangman
        app.kubernetes.io/version: '20201212'
        app.kubernetes.io/component: hangman
        app.kubernetes.io/part-of: games
        # app.kubernetes.io/managed-by: blazedpath
        enviroment: dev
        tier: frontend
      annotations:
        # prometheus.io/scrape: 'true'
        # prometheus.io/path: /metrics
        # prometheus.io/port: '8080'
        kubernetes.io/change-cause: '20201212'
    spec:
      containers:
        - name: hangman
          image: 'registry.gitlab.com/flaviolrita/p5-hangman:0.0.4'
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
          - configMapRef:
              name: hangman-config  
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 120
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 250m
              memory: 500Mi
      serviceAccountName: games
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate    
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hangman
  namespace: games
  labels:
    app.kubernetes.io/name: hangman
    app.kubernetes.io/instance: hangman
    app.kubernetes.io/version: '20201212'
    app.kubernetes.io/component: hangman
    app.kubernetes.io/part-of: games
    # app.kubernetes.io/managed-by: blazedpath
    enviroment: dev
    tier: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hangman
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
--- 
kind: Service
apiVersion: v1
metadata:
  name: hangman
  namespace: games
  labels:
    app.kubernetes.io/name: hangman
    app.kubernetes.io/instance: hangman
    app.kubernetes.io/version: '20201212'
    app.kubernetes.io/component: hangman
    app.kubernetes.io/part-of: games
    # app.kubernetes.io/managed-by: blazedpath
    enviroment: dev
    tier: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: hangman
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30009
      protocol: TCP
      name: hangman

# kind: Service
# apiVersion: v1
# metadata:
#   name: hangman
#   namespace: games
#   labels:
#     app.kubernetes.io/name: hangman
#     app.kubernetes.io/instance: hangman
#     app.kubernetes.io/version: '20201212'
#     app.kubernetes.io/component: hangman
#     app.kubernetes.io/part-of: games
#     # app.kubernetes.io/managed-by: blazedpath
#     enviroment: dev
#     tier: frontend
# spec:
#   type: ClusterIP
#   selector:
#     app.kubernetes.io/name: hangman
#   ports:
#     - port: 8000
#       targetPort: 8000
#       protocol: TCP
#       name: hangman
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: hangman
#   namespace: games
#   labels:
#     app.kubernetes.io/name: hangman
#     app.kubernetes.io/instance: hangman
#     app.kubernetes.io/version: '20201212'
#     app.kubernetes.io/component: hangman
#     app.kubernetes.io/part-of: games
#     # app.kubernetes.io/managed-by: blazedpath
#     enviroment: dev
#     tier: frontend
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     # cert-manager.io/cluster-issuer: letsencrypt-prod
#     # nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
#     # nginx.ingress.kubernetes.io/limit-connections: '20480'
#     # nginx.ingress.kubernetes.io/limit-rpm: '300'
#     # nginx.ingress.kubernetes.io/limit-burst-multiplier: '600'
# spec:
#   # tls:
#   #   - hosts:
#   #       - hangman.192.168.1.152.nip.io
#   #     secretName: dev-blazedpath-com-tls
#   rules:
#     - host: hangman.192.168.1.152.nip.io
#       http:
#         paths:
#           - backend:
#               serviceName: hangman
#               servicePort: 8000  